// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/v1/docklet.proto

package dockletv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DockletService_RegisterStream_FullMethodName = "/docklet.v1.DockletService/RegisterStream"
	DockletService_ListNodes_FullMethodName      = "/docklet.v1.DockletService/ListNodes"
	DockletService_ExecuteCommand_FullMethodName = "/docklet.v1.DockletService/ExecuteCommand"
)

// DockletServiceClient is the client API for DockletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DockletServiceClient interface {
	// Agent initiates a stream to the Hub.
	// This is a persistent bidirectional stream.
	RegisterStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamPayload, StreamPayload], error)
	// Admin API
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
}

type dockletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDockletServiceClient(cc grpc.ClientConnInterface) DockletServiceClient {
	return &dockletServiceClient{cc}
}

func (c *dockletServiceClient) RegisterStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamPayload, StreamPayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DockletService_ServiceDesc.Streams[0], DockletService_RegisterStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPayload, StreamPayload]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockletService_RegisterStreamClient = grpc.BidiStreamingClient[StreamPayload, StreamPayload]

func (c *dockletServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, DockletService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockletServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, DockletService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockletServiceServer is the server API for DockletService service.
// All implementations must embed UnimplementedDockletServiceServer
// for forward compatibility.
type DockletServiceServer interface {
	// Agent initiates a stream to the Hub.
	// This is a persistent bidirectional stream.
	RegisterStream(grpc.BidiStreamingServer[StreamPayload, StreamPayload]) error
	// Admin API
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	mustEmbedUnimplementedDockletServiceServer()
}

// UnimplementedDockletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockletServiceServer struct{}

func (UnimplementedDockletServiceServer) RegisterStream(grpc.BidiStreamingServer[StreamPayload, StreamPayload]) error {
	return status.Error(codes.Unimplemented, "method RegisterStream not implemented")
}
func (UnimplementedDockletServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedDockletServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedDockletServiceServer) mustEmbedUnimplementedDockletServiceServer() {}
func (UnimplementedDockletServiceServer) testEmbeddedByValue()                        {}

// UnsafeDockletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockletServiceServer will
// result in compilation errors.
type UnsafeDockletServiceServer interface {
	mustEmbedUnimplementedDockletServiceServer()
}

func RegisterDockletServiceServer(s grpc.ServiceRegistrar, srv DockletServiceServer) {
	// If the following call panics, it indicates UnimplementedDockletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockletService_ServiceDesc, srv)
}

func _DockletService_RegisterStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DockletServiceServer).RegisterStream(&grpc.GenericServerStream[StreamPayload, StreamPayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DockletService_RegisterStreamServer = grpc.BidiStreamingServer[StreamPayload, StreamPayload]

func _DockletService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockletServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockletService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockletServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockletService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockletServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockletService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockletServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DockletService_ServiceDesc is the grpc.ServiceDesc for DockletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docklet.v1.DockletService",
	HandlerType: (*DockletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _DockletService_ListNodes_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _DockletService_ExecuteCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterStream",
			Handler:       _DockletService_RegisterStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/docklet.proto",
}
